/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MoodScope;

import java.awt.BorderLayout;
import java.awt.Image;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import static javax.swing.JOptionPane.*;
import javax.swing.JPanel;

/**
 *
 * @author joseg
 */
public class AgregarEntrada extends javax.swing.JPanel {
    Usuario usuario;
    String nombre;
    private HashMap<String, String> valores;
   
    private DataContainer container;
    
    
    /**
     * Creates new form InicioSesion
     */
    public AgregarEntrada() {
        initComponents();
        usuario= new Usuario();
        nombre="";
        DataContainer dataContainer = General.dataContainer;
       
       valores = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        btnVolver = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(390, 850));

        contenedor.setBackground(new java.awt.Color(255, 255, 255));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MoodScope/logo5.png"))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Selecciona la fecha para registrar tu estado de ánimo:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(102, 102, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jCalendar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendar1PropertyChange(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(102, 102, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(54, 54, 54))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addGap(27, 27, 27)
                .addComponent(btnVolver)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
   

  
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        // Obtener el valor del TextField
        //container = new DataContainer();
        
        
        //String valor = jTextField1.getText();
        
        /*
        // Obtener la fecha actual
        LocalDate fechaActual = LocalDate.now();
        
        // Almacenar el valor y la fecha en el HashMap
        General.dataContainer.setDatos("Entrada: 1", "Fecha: " +valor);
        
        // Limpiar el TextField después de guardar el valor
        //txtValor.setText("");
        for (Map.Entry<String, String> entry : General.dataContainer.datos.entrySet()) {
            System.out.println("Clave: " + entry.getKey() + ", Valor: " + entry.getValue());
        }
        */
        
        String fecha = jTextField1.getText();
                valores.put("Fecha:", fecha);
                System.out.println("Texto guardado en HashMap: " + valores.get("Fecha:"));
           try {
        HashMapFileWriter.guardarHashMapEnArchivo(valores, "registro.txt");
        HashMapBinWritter.guardarHashMapEnArchivoBinario(valores, "registro.bin");
        
        System.out.println("HashMap guardado en el archivo 'registro.txt'");
        System.out.println("HashMap guardado en el archivo 'registro.bin'");
        
        } catch (IOException e) {
        System.out.println("Error al guardar el HashMap en el archivo 'registro.txt': " + e.getMessage());
        }
    
           
           
           
        
        Pregunta1 p1 = new Pregunta1();
        showPanel(p1);
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    public HashMap<String, String> getValores() {
        return valores;
    }
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCalendar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendar1PropertyChange
        //if (evt.getOldValue() != null){
            SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
            jTextField1.setText(ff.format(jCalendar1.getCalendar().getTime()));
        //}
        
    }//GEN-LAST:event_jCalendar1PropertyChange

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuPrincipal menuPrincipal= new MenuPrincipal();
        showPanel(menuPrincipal);
    }//GEN-LAST:event_btnVolverActionPerformed
    
    public void setImageIcon(JLabel labelName, String root){ //root ruta de la imagen
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
        image.getImage().getScaledInstance(labelName.getWidth(), 
                labelName.getHeight(), Image.SCALE_DEFAULT)
        );
        logo.setIcon(icon);//Asinarle el icono a la etiqueta
        this.repaint();//Actualizar la etiqueta y re-pintarla
        
    }
    private void guardarHashMapEnArchivo(HashMap<String, String> hashMap, String nombreArchivo) throws IOException {
        FileWriter writer = new FileWriter(nombreArchivo);
        for (Map.Entry<String, String> entry : hashMap.entrySet()) {
            writer.write(entry.getKey() + ": " + entry.getValue() + "\n");
        }
        writer.close();
    }
    //Mostrar los paneles
    private void showPanel (JPanel p){
        
        p.setSize(360,640);
        p.setLocation(0,0);
        contenedor.removeAll();
        contenedor.add(p, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel contenedor;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
