/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MoodScope;

import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;
import javax.swing.JPanel;

/**
 *
 * @author joseg
 */
public class Recomendaciones extends javax.swing.JPanel {
    Usuario usuario;
    String nombre;
    /**
     * Creates new form InicioSesion
     */
    public Recomendaciones() {
        initComponents();
        usuario= new Usuario();
        nombre="";
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAlimentacion = new javax.swing.JButton();
        btnDiversion = new javax.swing.JButton();
        btnSaludFisica = new javax.swing.JButton();
        btnHobbies = new javax.swing.JButton();
        btnSocial = new javax.swing.JButton();
        btnEjercicio = new javax.swing.JButton();
        btnTrabajoEstudio = new javax.swing.JButton();
        btnSuenio = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(390, 850));

        contenedor.setBackground(new java.awt.Color(255, 255, 255));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MoodScope/logo5.png"))); // NOI18N

        btnAlimentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MoodScope/alimentacion.png"))); // NOI18N
        btnAlimentacion.setPreferredSize(new java.awt.Dimension(128, 128));
        btnAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlimentacionActionPerformed(evt);
            }
        });

        btnDiversion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MoodScope/diversion.png"))); // NOI18N
        btnDiversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiversionActionPerformed(evt);
            }
        });

        btnSaludFisica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MoodScope/salud2.png"))); // NOI18N
        btnSaludFisica.setToolTipText("");
        btnSaludFisica.setPreferredSize(new java.awt.Dimension(223, 135));
        btnSaludFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaludFisicaActionPerformed(evt);
            }
        });

        btnHobbies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MoodScope/hobbies.png"))); // NOI18N
        btnHobbies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHobbiesActionPerformed(evt);
            }
        });

        btnSocial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MoodScope/social.png"))); // NOI18N
        btnSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSocialActionPerformed(evt);
            }
        });

        btnEjercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MoodScope/ejercicio.png"))); // NOI18N
        btnEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjercicioActionPerformed(evt);
            }
        });

        btnTrabajoEstudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MoodScope/trabajo.png"))); // NOI18N
        btnTrabajoEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabajoEstudioActionPerformed(evt);
            }
        });

        btnSuenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MoodScope/suenio.png"))); // NOI18N
        btnSuenio.setPreferredSize(new java.awt.Dimension(70, 71));
        btnSuenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuenioActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Salud Física");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Alimentación");

        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Diversión");

        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Tiempo libre/hobbies");

        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Social");

        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("Ejercicio");

        jLabel8.setText("Trabajo o Estudio");

        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("Sueño");

        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setText("Tabajo/Estudio");

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel7))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contenedorLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(btnSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(contenedorLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(9, 9, 9))
                                            .addComponent(jLabel10)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSaludFisica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTrabajoEstudio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAlimentacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(45, 45, 45)))
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnVolver)
                                    .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnSuenio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEjercicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addComponent(btnHobbies, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDiversion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel9))))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiversion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(btnSaludFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSuenio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTrabajoEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnHobbies, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addGap(232, 232, 232))))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuPrincipal menuPrincipal= new MenuPrincipal();
        showPanel(menuPrincipal);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlimentacionActionPerformed
        String titulo = "Recomendaciones para alimentación";
        int messageType = JOptionPane.INFORMATION_MESSAGE;
        showMessageDialog(null, "Estas son algunas recomendaciones para mejorar tu Alimentación: \n"+
                "•	Come regular y balanceado: Evita saltarte comidas y procura consumir alimentos de todos los grupos cada día.\n" +
"•	Hidrátate bien: Beber suficiente agua es esencial para el buen funcionamiento del cerebro y el cuerpo en general.\n" +
"•	Limita el consumo de alimentos procesados, azúcares refinados y grasas saturadas: Estos alimentos pueden empeorar el estado de ánimo y contribuir a la inflamación.", titulo, messageType);
    }//GEN-LAST:event_btnAlimentacionActionPerformed

    private void btnDiversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiversionActionPerformed
        String titulo = "Recomendaciones para diversión";
        int messageType = JOptionPane.INFORMATION_MESSAGE;
        showMessageDialog(null, "Estas son algunas recomendaciones para mejorar tu diversión:\n" +
"•	Leer un libro: Leer un buen libro puede ayudarte a transportarte a otro mundo y olvidarte del estrés de la vida diaria.\n" +
"•	Escuchar música: Escucha tu música favorita o prueba nuevos géneros musicales.\n" +
"•	Tomar un baño relajante: Agrega sales de Epsom o aceites esenciales a tu baño para una experiencia aún más relajante.\n" +
"•	Meditar o hacer yoga: La meditación y el yoga pueden ayudarte a calmar tu mente y reducir el estrés.\n" +
"Recuerda:\n" +
"•	Lo más importante es encontrar actividades que te gusten y que te hagan sentir bien.\n" +
"•	No tengas miedo de probar cosas nuevas.\n" +
"•	Si te sientes abrumado o estresado, tómate un tiempo para ti mismo y haz algo que te ayude a relajarte.", titulo, messageType);
    }//GEN-LAST:event_btnDiversionActionPerformed

    private void btnSaludFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaludFisicaActionPerformed
        String titulo = "Recomendaciones para salud física";
        int messageType = JOptionPane.INFORMATION_MESSAGE;
        showMessageDialog(null, "Estas son algunas recomendaciones para mejorar tu salud:\n" +
"•	Exposición a la luz solar: La luz solar puede influir en la producción de serotonina, un neurotransmisor asociado con la regulación del estado de ánimo. "
                + "\nIntenta pasar tiempo al aire libre todos los días, especialmente durante las horas del día.\n" +
"•	Limita el consumo de alcohol y cafeína: El consumo excesivo de alcohol y cafeína puede afectar negativamente tu estado de ánimo. "
                + "\nIntenta limitar la ingesta de estas sustancias y asegúrate de mantener una hidratación adecuada.", titulo, messageType);
    }//GEN-LAST:event_btnSaludFisicaActionPerformed

    private void btnHobbiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHobbiesActionPerformed
        String titulo = "Recomendaciones para tiempo libre o hobbies";
        int messageType = JOptionPane.INFORMATION_MESSAGE;
        showMessageDialog(null, "Estas son algunas recomendaciones para mejorar tu tiempo libre o hobbies:\n" +
"•	Practica actividades que disfrutes: Dedica tiempo a actividades que te gusten y te hagan sentir bien, ya sea leer, escuchar música, "
                + "\ndibujar o cualquier otra actividad creativa o recreativa que te traiga alegría.", titulo, messageType);
    }//GEN-LAST:event_btnHobbiesActionPerformed

    private void btnSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSocialActionPerformed
        String titulo = "Recomendaciones para vida social";
        int messageType = JOptionPane.INFORMATION_MESSAGE;
        showMessageDialog(null, "Estas son algunas recomendaciones para mejorar tu vida social:\n" +
"•	Quedar con amigos o familiares: Pasar tiempo con tus seres queridos es una excelente manera de combatir la soledad y mejorar tu estado de ánimo.\n" +
"•	Unirse a un club o grupo: Encuentra un club o grupo que te interese, como un club de lectura, un equipo deportivo o un grupo de voluntarios.\n" +
"•	Ir a un evento: Asiste a un concierto, una obra de teatro, un partido deportivo o cualquier otro evento que te guste.\n" +
"•	Tomar una clase: Aprende algo nuevo tomando una clase de cocina, baile, pintura o cualquier otra cosa que te interese.", titulo, messageType);
    }//GEN-LAST:event_btnSocialActionPerformed

    private void btnEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjercicioActionPerformed
        String titulo = "Recomendaciones para Ejercicio";
        int messageType = JOptionPane.INFORMATION_MESSAGE;
        showMessageDialog(null, "Estas son algunas recomendaciones para mejorar la realización de deportes y ejercicio:\n" +
"•	Realiza actividad física regularmente: El ejercicio libera endorfinas, que tienen un efecto positivo en el estado de ánimo. "
                + "\nAdemás, la actividad física ayuda a reducir el estrés, la ansiedad y los síntomas de depresión.\n" +
"•	Encuentra una actividad que te guste: No tiene que ser un deporte extremo. Puedes elegir actividades como caminar, bailar, nadar, andar en bicicleta o hacer yoga.\n" +
"•	Comienza poco a poco: Si no estás acostumbrado a hacer ejercicio, comienza con sesiones cortas y aumenta gradualmente la intensidad y la duración a medida que te sientas más cómodo.", titulo, messageType);
    }//GEN-LAST:event_btnEjercicioActionPerformed

    private void btnTrabajoEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabajoEstudioActionPerformed
        String titulo = "Recomendaciones para Trabajo o Estudio";
        int messageType = JOptionPane.INFORMATION_MESSAGE;
        showMessageDialog(null, "Estas son algunas recomendaciones para mejorar tu trabajo o estudio:\n" +
"•	Mantén un espacio de trabajo ordenado y limpio: Un espacio organizado puede ayudarte a concentrarte mejor y reducir el estrés.\n" +
"•	Asegúrate de tener una buena iluminación y ventilación: La luz natural y el aire fresco pueden mejorar tu estado de ánimo y tu productividad.\n" +
"•	Personaliza tu espacio de trabajo: Agrega elementos que te inspiren y te hagan sentir cómodo, como fotos, plantas o decoraciones.\n" +
"•	Toma descansos regulares: Levántate y muévete cada 30-60 minutos para evitar la fatiga mental y física. "
                + "\nAprovecha los descansos para tomar un poco de aire fresco, estirarte o hacer algo que te relaje.", titulo, messageType);
    }//GEN-LAST:event_btnTrabajoEstudioActionPerformed

    private void btnSuenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuenioActionPerformed
        String titulo = "Recomendaciones para sueño";
        int messageType = JOptionPane.INFORMATION_MESSAGE;
        showMessageDialog(null, "Estas son algunas recomendaciones para mejorar tu sueño:\n" +
"•	Duerme lo suficiente: La mayoría de los adultos necesitan alrededor de 7-8 horas de sueño por noche. "
                + "\nLa falta de sueño puede afectar negativamente tu estado de ánimo, energía, concentración y memoria.\n" +
"•	Establece una rutina de sueño regular: Acuéstate y levántate a la misma hora todos los días, incluso los fines de semana. "
                + "\nEsto ayudará a regular tu reloj circadiano y mejorar la calidad de tu sueño.\n" +
"•	Crea un ambiente de sueño adecuado: Asegúrate de que tu habitación esté oscura, silenciosa y fresca. "
                + "\nEvita usar dispositivos electrónicos en la cama, ya que la luz azul puede interferir con el sueño.", titulo, messageType);
    }//GEN-LAST:event_btnSuenioActionPerformed
    
    public void setImageIcon(JLabel labelName, String root){ //root ruta de la imagen
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
        image.getImage().getScaledInstance(labelName.getWidth(), 
                labelName.getHeight(), Image.SCALE_DEFAULT)
        );
        logo.setIcon(icon);//Asinarle el icono a la etiqueta
        this.repaint();//Actualizar la etiqueta y re-pintarla
        
    }
    
    //Mostrar los paneles
    private void showPanel (JPanel p){
        
        p.setSize(360,640);
        p.setLocation(0,0);
        contenedor.removeAll();
        contenedor.add(p, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlimentacion;
    private javax.swing.JButton btnDiversion;
    private javax.swing.JButton btnEjercicio;
    private javax.swing.JButton btnHobbies;
    private javax.swing.JButton btnSaludFisica;
    private javax.swing.JButton btnSocial;
    private javax.swing.JButton btnSuenio;
    private javax.swing.JButton btnTrabajoEstudio;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
